#ifndef __DPL_INTRINSICS_H
#define __DPL_INTRINSICS_H

typedef enum
{
    INTRINSIC_BOOLEAN_PRINT,
    INTRINSIC_BOOLEAN_TOSTRING,

    INTRINSIC_NUMBER_PRINT,
    INTRINSIC_NUMBER_TOSTRING,
    INTRINSIC_NUMBERITERATOR_NEXT,
    INTRINSIC_NUMBERRANGE_ITERATOR,

    INTRINSIC_STRING_LENGTH,
    INTRINSIC_STRING_PRINT,

    INTRINSIC_ARRAY_LENGTH,
    INTRINSIC_ARRAY_ELEMENT,
    INTRINSIC_ARRAY_ITERATOR,

    INTRINSIC_ARRAYITERATOR_NEXT,

    COUNT_INTRINSICS,
} DPL_Intrinsic_Kind;

const char *dpl_intrinsic_kind_name(DPL_Intrinsic_Kind kind);

#endif // __DPL_INTRINSICS_H